development:
  forest_env_secret: c8cfeeae1c741049813e0f856396f72858022fb43bc3aae1cb29ce632b8d8f99
  forest_auth_secret: FNC7-U7BIGq3yfH4jk1y4w
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
